"""Zen-themed MI_* for M_Master_Toon_Universal — moss, ink, bamboo, sakura path, torii, etc.

Uses Japanese ornament alphas from /Game/Textures/70_Japanese_Ornament_Alphas_vfxMed
and Sakura/Magical glyph fallbacks where noted.
"""
from __future__ import annotations

import material_lib as lib

MASTER = f"{lib.MASTER_DIR}/M_Master_Toon_Universal.M_Master_Toon_Universal"
ZEN_DIR = f"{lib.MATERIALS_ROOT}/Instances/Environment/Zen"

ZEN_INSTANCES: list[dict] = [
    {
        "name": "MI_Zen_MossGarden",
        "folder": ZEN_DIR,
        "purpose": "Zen — mossy stone garden with minimal circle motif",
        "profile": "TP_Stone",
        "vectors": {"BaseTint": (0.42, 0.48, 0.38, 1.0)},
        "scalars": {
            "TextureWeight": 0.75,
            "Roughness": 0.88,
            "TriplanarTiling": 280.0,
            "MacroVariationStrength": 0.45,
            "MotifScale": 3.0,
        },
        "switches": {"bTriplanar": True},
        "textures": {"MotifMask": "zen01", "FairyGlyphMask": "zen03"},
    },
    {
        "name": "MI_Zen_InkWash",
        "folder": ZEN_DIR,
        "purpose": "Zen — ink wash calm with wave glyph on pale stone",
        "profile": "TP_Default",
        "vectors": {"BaseTint": (0.82, 0.8, 0.76, 1.0)},
        "scalars": {
            "TextureWeight": 0.2,
            "Roughness": 0.72,
            "InkIntensity": 0.65,
            "StrokeStrength": 0.35,
            "MotifScale": 4.0,
            "RimSoftness": 0.85,
        },
        "textures": {"MotifMask": "zen07", "FairyGlyphMask": "zen07"},
    },
    {
        "name": "MI_Zen_BambooMist",
        "folder": ZEN_DIR,
        "purpose": "Zen — bamboo motif in soft morning mist",
        "profile": "TP_Default",
        "vectors": {
            "BaseTint": (0.68, 0.72, 0.65, 1.0),
            "RimColor": (0.92, 0.95, 0.88, 1.0),
        },
        "scalars": {
            "TextureWeight": 0.35,
            "Roughness": 0.78,
            "PastelLift": 0.2,
            "RimIntensity": 0.55,
            "RimPower": 2.0,
            "MotifScale": 5.0,
        },
        "textures": {"MotifMask": "zen23", "FairyGlyphMask": "zen23"},
    },
    {
        "name": "MI_Zen_Karesansui",
        "folder": ZEN_DIR,
        "purpose": "Zen — dry garden sand ripples, minimal ornament",
        "profile": "TP_Stone",
        "vectors": {"BaseTint": (0.58, 0.56, 0.52, 1.0)},
        "scalars": {
            "TextureWeight": 0.65,
            "Roughness": 0.92,
            "TriplanarTiling": 200.0,
            "DetailStrength": 0.25,
            "DetailTiling": 6.0,
            "MotifScale": 2.5,
        },
        "switches": {"bTriplanar": True},
        "textures": {"MotifMask": "zen35", "FairyGlyphMask": "zen30"},
    },
    {
        "name": "MI_Zen_ToriiVermillion",
        "folder": ZEN_DIR,
        "purpose": "Zen — torii gate vermillion with restrained circle accent",
        "profile": "TP_Default",
        "vectors": {
            "BaseTint": (0.72, 0.18, 0.14, 1.0),
            "RimColor": (1.0, 0.55, 0.42, 1.0),
            "MotifColor": (0.85, 0.22, 0.18, 1.0),
        },
        "scalars": {
            "TextureWeight": 0.45,
            "Roughness": 0.62,
            "MotifScale": 3.5,
            "RimIntensity": 0.65,
            "RimPower": 2.8,
            "DetailStrength": 0.15,
        },
        "textures": {"MotifMask": "zen03", "FairyGlyphMask": "zen01"},
    },
    {
        "name": "MI_Zen_SakuraDrift",
        "folder": ZEN_DIR,
        "purpose": "Zen — sakura path blossom drift on pale garden stone",
        "profile": "TP_Default",
        "vectors": {
            "BaseTint": (0.88, 0.82, 0.84, 1.0),
            "MotifColor": (1.0, 0.72, 0.82, 1.0),
            "RimColor": (1.0, 0.9, 0.95, 1.0),
        },
        "scalars": {
            "TextureWeight": 0.28,
            "Roughness": 0.68,
            "PastelLift": 0.3,
            "MotifScale": 6.0,
            "RimIntensity": 0.5,
            "SparkleIntensity": 0.35,
            "SparkleScale": 12.0,
        },
        "textures": {"MotifMask": "zen07", "FairyGlyphMask": "flower", "SparkleMask": "twinkle"},
    },
    {
        "name": "MI_Zen_LanternWarm",
        "folder": ZEN_DIR,
        "purpose": "Zen — stone lantern base with warm paper glow motes",
        "profile": "TP_Stone",
        "vectors": {
            "BaseTint": (0.52, 0.48, 0.44, 1.0),
            "RimColor": (1.0, 0.78, 0.45, 1.0),
            "SparkleColor": (1.0, 0.85, 0.55, 1.0),
        },
        "scalars": {
            "TextureWeight": 0.55,
            "Roughness": 0.82,
            "TriplanarTiling": 240.0,
            "RimIntensity": 0.85,
            "SparkleIntensity": 0.9,
            "SparkleScale": 8.0,
            "MotifScale": 3.0,
        },
        "switches": {"bTriplanar": True},
        "textures": {"MotifMask": "zen30", "FairyGlyphMask": "zen03", "SparkleMask": "glow"},
    },
    {
        "name": "MI_Zen_TeaHouseCedar",
        "folder": ZEN_DIR,
        "purpose": "Zen — tea house cedar wood with bamboo lattice hint",
        "profile": "TP_Default",
        "vectors": {"BaseTint": (0.48, 0.36, 0.26, 1.0)},
        "scalars": {
            "TextureWeight": 0.5,
            "Roughness": 0.74,
            "MacroVariationStrength": 0.35,
            "MotifScale": 4.5,
            "DetailStrength": 0.2,
        },
        "textures": {"MotifMask": "zen23", "FairyGlyphMask": "zen05"},
    },
    {
        "name": "MI_Zen_PondStill",
        "folder": ZEN_DIR,
        "purpose": "Zen — still pond edge stone with subtle wave ripple",
        "profile": "TP_Stone",
        "vectors": {
            "BaseTint": (0.45, 0.5, 0.52, 1.0),
            "RimColor": (0.75, 0.88, 0.92, 1.0),
        },
        "scalars": {
            "TextureWeight": 0.4,
            "Roughness": 0.35,
            "TriplanarTiling": 180.0,
            "RimIntensity": 0.45,
            "RimSoftness": 0.9,
            "MotifScale": 2.8,
            "Metallic": 0.08,
        },
        "switches": {"bTriplanar": True},
        "textures": {"MotifMask": "zen07", "FairyGlyphMask": "zen02"},
    },
    {
        "name": "MI_Zen_ShojiPaper",
        "folder": ZEN_DIR,
        "purpose": "Zen — shoji rice paper screen, near-flat wash",
        "profile": "TP_Default",
        "vectors": {"BaseTint": (0.94, 0.92, 0.86, 1.0)},
        "scalars": {
            "TextureWeight": 0.12,
            "Roughness": 0.9,
            "InkIntensity": 0.25,
            "StrokeStrength": 0.15,
            "MotifScale": 5.5,
            "RimSoftness": 1.0,
        },
        "textures": {"MotifMask": "zen01", "FairyGlyphMask": "zen01"},
    },
    {
        "name": "MI_Zen_TempleStep",
        "folder": ZEN_DIR,
        "purpose": "Zen — worn temple stone steps, moss in recesses",
        "profile": "TP_Stone",
        "vectors": {"BaseTint": (0.5, 0.52, 0.48, 1.0)},
        "scalars": {
            "TextureWeight": 0.7,
            "Roughness": 0.9,
            "TriplanarTiling": 320.0,
            "MacroVariationStrength": 0.5,
            "DetailStrength": 0.35,
            "MotifScale": 2.2,
        },
        "switches": {"bTriplanar": True},
        "textures": {"MotifMask": "zen30", "FairyGlyphMask": "zen35"},
    },
    {
        "name": "MI_Zen_MoonlitGarden",
        "folder": ZEN_DIR,
        "purpose": "Zen — moonlit garden cool stone with soft glyph shimmer",
        "profile": "TP_Default",
        "vectors": {
            "BaseTint": (0.38, 0.42, 0.52, 1.0),
            "RimColor": (0.72, 0.78, 0.95, 1.0),
            "MotifColor": (0.65, 0.72, 0.88, 1.0),
        },
        "scalars": {
            "TextureWeight": 0.32,
            "Roughness": 0.75,
            "RimIntensity": 0.7,
            "RimPower": 3.0,
            "MotifScale": 4.0,
            "SparkleIntensity": 0.5,
            "SparkleScale": 14.0,
        },
        "textures": {"MotifMask": "zen03", "FairyGlyphMask": "moon", "SparkleMask": "twinkle"},
    },
    {
        "name": "MI_Zen_RojiPath",
        "folder": ZEN_DIR,
        "purpose": "Zen — roji dew-path slab with damp edge stones (GB_ZEN_ROJI_STEP)",
        "profile": "TP_Stone",
        "vectors": {"BaseTint": (0.55, 0.54, 0.5, 1.0)},
        "scalars": {
            "TextureWeight": 0.62,
            "Roughness": 0.86,
            "TriplanarTiling": 260.0,
            "MacroVariationStrength": 0.4,
            "DetailStrength": 0.3,
            "MotifScale": 2.4,
        },
        "switches": {"bTriplanar": True},
        "textures": {"MotifMask": "zen35", "FairyGlyphMask": "zen30"},
    },
    {
        "name": "MI_Zen_TsukubaiBasin",
        "folder": ZEN_DIR,
        "purpose": "Zen — tsukubai basin stone, dark wet recess (GB_ZEN_TSUKUBAI)",
        "profile": "TP_Stone",
        "vectors": {
            "BaseTint": (0.38, 0.4, 0.42, 1.0),
            "RimColor": (0.62, 0.7, 0.75, 1.0),
        },
        "scalars": {
            "TextureWeight": 0.55,
            "Roughness": 0.42,
            "TriplanarTiling": 200.0,
            "RimIntensity": 0.55,
            "RimSoftness": 0.85,
            "MotifScale": 2.0,
            "Metallic": 0.06,
        },
        "switches": {"bTriplanar": True},
        "textures": {"MotifMask": "zen02", "FairyGlyphMask": "zen07"},
    },
    {
        "name": "MI_Zen_ToriiGreybox",
        "folder": ZEN_DIR,
        "purpose": "Zen — weathered torii lacquer for modular gate greybox (GB_ZEN_TORII_GATE)",
        "profile": "TP_Default",
        "vectors": {
            "BaseTint": (0.58, 0.14, 0.1, 1.0),
            "RimColor": (0.95, 0.45, 0.35, 1.0),
            "MotifColor": (0.72, 0.2, 0.15, 1.0),
        },
        "scalars": {
            "TextureWeight": 0.5,
            "Roughness": 0.68,
            "MotifScale": 3.2,
            "RimIntensity": 0.6,
            "RimPower": 2.5,
            "MacroVariationStrength": 0.3,
            "DetailStrength": 0.18,
        },
        "textures": {"MotifMask": "zen01", "FairyGlyphMask": "zen03"},
    },
]

ZEN_NAMES = frozenset(spec["name"] for spec in ZEN_INSTANCES)
